repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-added-large-files
      - id: detect-private-key
      - id: no-commit-to-branch
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.3.2" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
