name: Build 1-Click App image
description: Builds an OCA app from Packer configuration and saves the snapshot for subsequent internal Hetzner Cloud platform use.
inputs:
  app:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # validate Packer templates
    - name: Validate Packer template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: apps/hetzner/${{ inputs.app }}/

    # build artifact
    - name: Build
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: "-color=false -on-error=abort"
        target: apps/hetzner/${{ inputs.app }}/
      env:
        HCLOUD_API_TOKEN: ${{ github.ref == 'refs/heads/main' && secrets.HCLOUD_API_TOKEN || secrets.HCLOUD_API_TOKEN_STAGING }}

    - run: ./.github/cleanup.sh ${{ inputs.app }}
      env:
        HCLOUD_TOKEN: ${{ github.ref == 'refs/heads/main' && secrets.HCLOUD_API_TOKEN || secrets.HCLOUD_API_TOKEN_STAGING }}
