---
name: hetzner/docker-ce

on:
  push:
    paths:
      - "apps/hetzner/docker-ce/**"
      - ".github/workflows/packer-docker-ce.yml"
      - "apps/shared/**"
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  packer:
    runs-on: [self-hosted, Linux, X64]
    name: packer
    steps:
      - uses: ./.github/actions/build-image
        with:
          app: docker-ce
