---
name: hetzner/wordpress

on:
  workflow_dispatch:
  push:
    paths:
      - "apps/hetzner/wordpress/**"
      - ".github/workflows/packer-wordpress.yml"
      - "apps/shared/**"

jobs:
  packer:
    runs-on: [self-hosted, Linux, X64]
    name: packer
    steps:
      - uses: ./.github/actions/build-image
        with:
          app: wordpress
