---
name: hetzner/big-blue-button

on:
  push:
    paths:
      - "apps/hetzner/big-blue-button/**"
      - ".github/workflows/packer-big-blue-button.yml"
      - "apps/shared/**"
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  packer:
    runs-on: [self-hosted, Linux, X64]
    name: packer
    steps:
      - uses: ./.github/actions/build-image
        with:
          app: big-blue-button
